# coding: utf-8

from __future__ import absolute_import

from typing import List

from api_server.entities.base_model_ import Model
from api_server.entities.ws_hotel_prob.inline_response200_probabilities import \
    InlineResponse200Probabilities
from api_server.util import deserialize_model


class BookProbResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self, probabilities: List[InlineResponse200Probabilities] = None):
        """
        BookProbResponse - a model defined in Swagger

        :param probabilities: The probabilities of this BookProbResponse.
        :type probabilities: List[InlineResponse200Probabilities]
        """
        self.swagger_types = {
            'probabilities': List[InlineResponse200Probabilities]
        }

        self.attribute_map = {
            'probabilities': 'probabilities'
        }

        self._probabilities = probabilities

    @classmethod
    def from_dict(cls, dikt) -> 'BookProbResponse':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The bookProbResponse of this BookProbResponse.
        :rtype: BookProbResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def probabilities(self) -> List[InlineResponse200Probabilities]:
        """
        Gets the probabilities of this BookProbResponse.

        :return: The probabilities of this BookProbResponse.
        :rtype: List[InlineResponse200Probabilities]
        """
        return self._probabilities

    @probabilities.setter
    def probabilities(self, probabilities: List[InlineResponse200Probabilities]):
        """
        Sets the probabilities of this BookProbResponse.

        :param probabilities: The probabilities of this BookProbResponse.
        :type probabilities: List[InlineResponse200Probabilities]
        """

        self._probabilities = probabilities
